# controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opal-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opal-controller
  template:
    metadata:
      labels:
        app: opal-controller
    spec:
      containers:
        - name: manager
          image: your-docker-image:tag
          command:
            - /manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
