# permissions for end users to view opaldeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opaldeployment-viewer-role
rules:
- apiGroups:
  - opal.example.com
  resources:
  - opaldeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opal.example.com
  resources:
  - opaldeployments/status
  verbs:
  - get
