apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: opaldeployments.opal.example.com
spec:
  group: opal.example.com
  names:
    kind: OPALDeployment
    listKind: OPALDeploymentList
    plural: opaldeployments
    singular: opaldeployment
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              size:
                type: integer
